#!/usr/bin/env php
<?php declare(strict_types=1);
namespace AoC;

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$application = new Application('Advent of Code 2021');
$application->add(new Command\Solve());
$application->run();
